spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://librarydb.ctaygwugsg84.ap-northeast-2.rds.amazonaws.com:3306/library_project?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: countingstar
jwt:
  issuer: 20213070@gs.cwnu.ac.kr
  secret_key: library_project
